forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'


# Mostly backwards compat with old MCO module
mod 'puppetlabs/mcollective', "1.1.6",
   :github_tarball => 'puppetlabs/puppetlabs-mcollective'

mod 'richardc/datacat'
mod 'puppetlabs/rabbitmq'
mod 'puppetlabs/activemq'
mod 'garethr/erlang'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/java_ks'
mod 'puppetlabs/vcsrepo'

# NGINX
mod 'jfryman/nginx'


mod 'puppetlabs/haproxy'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
